# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: None

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml

build:
  stage: build
  tags:
    - VM
    - amd64
  image: storage.kde.org/vm-images/kde-linux-builder
  script:
    - sudo ./bootstrap.sh
    - ./make-packages.sh
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - ${CI_PROJECT_DIR}/artifacts
      - ${CI_PROJECT_DIR}/logs
