# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: None

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml

Build Docker Image:
  stage: .pre
  tags:
    - kde-linux-x86_64
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --build-arg "PROJECT_DIR=${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
        --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
    - changes:
      - Dockerfile

Build in Docker:
  stage: build
  tags:
    - kde-linux-x86_64
  image: ${CI_REGISTRY_IMAGE}:latest
  script: ./make-packages.sh
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - ${CI_PROJECT_DIR}/artifacts
      - ${CI_PROJECT_DIR}/logs
