# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: None

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/blocks/workflow.yml

build:
  stage: build
  tags:
    - VM
    - amd64
  rules:
    - !reference [.default_rules, rules]
  image: storage.kde.org/vm-images/kde-linux-builder
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  script:
    - sudo ./bootstrap.sh
  artifacts:
    untracked: false
    when: always
    access: all
    paths:
      - ${CI_PROJECT_DIR}/logs
