# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: none

# The user configuration for CI builds.
# https://docs.buildstream.build/master/using_config.html

projects:
  freedesktop-sdk:
    # - Augment fd-sdk with our own caches as well so that we can catch objects that have fallen out of the remote cache or aren't there yet.
    # - As a fallback try to use our proxy cache for fd-sdk
    artifacts:
      override-project-caches: true
      servers:
        - url: https://buildstream.cache.kde-linux.haraldsitter.eu:11001
        - url: https://freedesktop.buildstream.cache.kde-linux.haraldsitter.eu
    source-caches:
      override-project-caches: true
      servers:
        - url: https://buildstream.cache.kde-linux.haraldsitter.eu:11001
        - url: https://freedesktop.buildstream.cache.kde-linux.haraldsitter.eu
  gnome:
    # - Augment gnome with our own caches as well so that we can catch objects that have fallen out of the remote cache or aren't there yet.
    # - As a fallback try to use our proxy cache for gnome
    artifacts:
      override-project-caches: true
      servers:
        - url: https://buildstream.cache.kde-linux.haraldsitter.eu:11001
        - url: https://gnome.buildstream.cache.kde-linux.haraldsitter.eu
    source-caches:
      override-project-caches: true
      servers:
        - url: https://buildstream.cache.kde-linux.haraldsitter.eu:11001
        - url: https://gnome.buildstream.cache.kde-linux.haraldsitter.eu

logging:
  # Be more verbose when things fail. In particular the kde-builder issue may be a ways back in the log.
  error-lines: 1000
